baseURL = "https://www.yacin.org/"
title = "ياسين"
theme = "zahi"
languageCode = "ar"
defaultContentLanguage = "ar"
enableRobotsTXT = true

[taxonomies]
  tag = "tags"

  [menu]
    [[menu.main]]
      identifier = "الرئيسية"
        name = "الرئيسية"
          url = "/"
            weight = 10

              [[menu.main]]
                identifier = "المقالات"
                  name = "المدونه"
                    url = "/posts"
                      weight = 20

                      [params]
                        github = "https://www.github.com/"
                          mail = "mailto:ben.yacin@gmail.com"
                            site = "https://yacin.org/"
                              description = "مدونة ياسين: مقالات تقنية وتربوية"
                                keywords = ["مدونة", "تقنية", "تربية", "ياسين"]

                                [sitemap]
                                  changefreq = "weekly"    # يمكنك تغييره إلى daily إذا كان لديك محتوى يومي
                                    priority = 0.5
                                      filename = "sitemap.xml"

                                      [services]
                                        [services.disqus]
                                          shortname = "yacinorg"
                                        [services.googleAnalytics]
                                            id = "G-0B6Z8WBZE"    # ضع هنا Measurement ID من GA4
