baseURL = "https://yacin.org/"
title = "ياسين"
theme = "zahi"
languageCode = "ar"
defaultContentLanguage = "ar"

[taxonomies]
tag = "tags"

[menu]
[[menu.main]]
identifier = "الرئيسية"
name = "الرئيسية"
url = "/"
weight = 10


[[menu.main]]
identifier = "المقالات"
name = "المدونه"
url = "/posts"
weight = 10


[params]
github = "https://www.github.com/"
mail = "mailto:ben.yacin@gmail.com"
site = "https://yacin.org/"


[services]
[services.disqus]
shortname = 'foobar'